// Simple Chinese localization for EFT DMA Radar (read-only, for SPT offline study use)
// Add more strings here as needed.

namespace eft_dma_radar.Silk.Misc.Localization
{
    public static class Chinese
    {
        // ==================== Map Names ====================
        public static readonly Dictionary<string, string> MapNames = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Customs"] = "海关",
            ["Factory"] = "工厂",
            ["Interchange"] = "立交桥",
            ["Lighthouse"] = "灯塔",
            ["Reserve"] = "储备站",
            ["Shoreline"] = "海岸线",
            ["Streets"] = "街区",
            ["Woods"] = "森林",
            ["Labs"] = "实验室",
            ["Ground Zero"] = "地面零点",
            ["Labyrinth"] = "迷宫",

            // Internal map IDs
            ["bigmap"] = "海关",
            ["factory4_day"] = "工厂",
            ["factory4_night"] = "工厂",
            ["interchange"] = "立交桥",
            ["rezervbase"] = "储备站",
            ["woods"] = "森林",
            ["lighthouse"] = "灯塔",
            ["shoreline"] = "海岸线",
            ["tarkovstreets"] = "街区",
            ["laboratory"] = "实验室",
            ["sandbox"] = "地面零点",
            ["Sandbox"] = "地面零点",
            ["Sandbox_high"] = "地面零点",
        };

        public static string GetMapName(string mapId)
        {
            if (string.IsNullOrEmpty(mapId))
                return mapId;

            return MapNames.TryGetValue(mapId, out var cn) ? cn : mapId;
        }

        // ==================== Player Types ====================
        public static readonly Dictionary<string, string> PlayerTypes = new(StringComparer.OrdinalIgnoreCase)
        {
            ["PMC"] = "PMC",
            ["Scav"] = "普通散兵",
            ["PlayerScav"] = "玩家散兵",
            ["Raider"] = "袭击者",
            ["Rogue"] = "叛军",
            ["Boss"] = "Boss",
            ["Cultist"] = "邪教徒",
            ["Follower"] = "追随者",
            ["Guard"] = "守卫",
            ["SniperScav"] = "狙击手散兵",
        };

        // ==================== Common UI / Panel Titles ====================
        public static readonly Dictionary<string, string> Ui = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Players"] = "玩家",
            ["Loot"] = "物资",
            ["Settings"] = "设置",
            ["Quests"] = "任务",
            ["ESP"] = "透视",
            ["Map"] = "地图",
            ["Hotkeys"] = "热键",
            ["Presets"] = "预设",
            ["Quest Zones"] = "任务区域",
            ["General"] = "通用",

            ["PlayersTab"] = "玩家列表",
            ["LootTab"] = "物资过滤",
            ["Aimview"] = "瞄准视角",
            ["Killfeed"] = "击杀播报",
            ["Hideout"] = "藏身处",
            ["Quest Planner"] = "任务规划器",
            ["Player History"] = "玩家历史",
            ["Watchlist"] = "监视列表",

            ["Enable"] = "启用",
            ["Disabled"] = "禁用",
            ["Master Toggle"] = "总开关",

            // Sidebar / common panel chrome
            ["Hide sidebar"] = "隐藏侧边栏",
            ["Show sidebar"] = "显示侧边栏",

            // Killfeed
            ["Killfeed"] = "击杀播报",
            ["No kills detected yet this raid."] = "本对局尚未检测到击杀。",
            ["Radar Overlay"] = "雷达叠加",
            ["Draw the killfeed overlay on the radar canvas."] = "在雷达画布上绘制击杀播报叠加。",
            ["Max"] = "最大",
            ["Maximum killfeed entries shown (1–20)."] = "显示的最大击杀播报条目数（1–20）。",
            ["TTL (s)"] = "存活时间 (秒)",
            ["Seconds before a killfeed entry expires."] = "击杀播报条目过期前的秒数。",
            ["Clear"] = "清除",
            ["Age"] = "时间",
            ["Killer"] = "击杀者",
            ["Victim"] = "受害者",
            ["Lvl"] = "等级",
            ["Weapon"] = "武器",

            // Common quest / hideout / history
            ["Refresh"] = "刷新",
            ["Search"] = "搜索",
            ["Filter"] = "筛选",
            ["Clear Filters"] = "清除筛选",
            ["No data"] = "无数据",
            ["Objectives"] = "目标",
            ["Keys"] = "钥匙",
            ["Items"] = "物品",
            ["Completed"] = "已完成",
            ["In Progress"] = "进行中",

            // HideoutPanel common
            ["Press Refresh to scan hideout..."] = "按刷新扫描藏身处...",
            ["Grouped"] = "分组",
            ["Upgrades"] = "升级",
            ["Planner"] = "规划器",
            ["Stash"] = "保险箱",
            ["Shopping List"] = "购物清单",
            ["Hide done"] = "隐藏已完成",
            ["FiR only"] = "仅 FiR",
            ["Refresh"] = "刷新",
            ["Area"] = "区域",
            ["Level"] = "等级",
            ["Progress"] = "进度",
            ["Requirements"] = "需求",
            ["Still Need"] = "仍需",
            ["Have"] = "已有",
            ["Trader"] = "商人",
            ["Total Value"] = "总价值",
            ["No stash items"] = "无保险箱物品",
            ["No upgrades in progress"] = "无进行中的升级",
            ["No shopping list items"] = "无购物清单物品",
            ["Station"] = "站点",

            // Top menu bar / command bar (上侧边栏 / 主菜单栏)
            ["Preset"] = "预设",
            ["○ Free"] = "○ 自由",
            ["◉ Follow"] = "◉ 跟随",
            ["Free pan — drag to move"] = "自由平移 — 拖动移动",
            ["Camera follows your player"] = "相机跟随你的玩家",
            ["⚔ Battle"] = "⚔ 战斗",
            ["Battle Mode ON — hide loot / corpses / doors"] = "战斗模式开启 — 隐藏物资/尸体/门",
            ["Battle Mode OFF — click for player-only view"] = "战斗模式关闭 — 点击仅玩家视图",
            ["→ Aim"] = "→ 瞄准线",
            ["Aimlines on/off"] = "瞄准线 开/关",
            ["◆ Loot"] = "◆ 物资",
            ["Loot markers on/off"] = "物资标记 开/关",
            ["▲ Exfils"] = "▲ 撤离点",
            ["Exfil points on/off"] = "撤离点 开/关",
            ["↻"] = "↻",
            ["Restart the radar (re-detect game world, players, loot)"] = "重启雷达（重新检测游戏世界、玩家、物资）",
            ["Only available during a raid or in the hideout"] = "仅在活动对局或藏身处中可用",
            ["⋯ More"] = "⋯ 更多",
            ["Other layers, panels, and overlays"] = "其他图层、面板和叠加",
            ["Radar Layers"] = "雷达图层",
            ["□ Doors"] = "□ 门",
            ["✈ Airdrops"] = "✈ 空投",
            ["⚡ Switches"] = "⚡ 开关",
            ["Player Display"] = "玩家显示",
            ["─ Connect Groups"] = "─ 连接组",
            ["Draw lines between squad members"] = "在小队成员之间绘制连线",
            ["⚠ High Alert"] = "⚠ 高警戒",
            ["Extend aimline when an enemy is looking at you"] = "当敌人瞄准你时延长瞄准线",
            ["Panels"] = "面板",
            ["▣ Loot Filters"] = "▣ 物资过滤",
            ["⌨ Hotkeys"] = "⌨ 热键",
            ["⌂ Hideout"] = "⌂ 藏身处",
            ["❁ Quest Planner"] = "❁ 任务规划器",
            ["☰ Player History"] = "☰ 玩家历史",
            ["⌕ Watchlist"] = "⌕ 监视列表",
            ["⊞ Map Generator"] = "⊞ 地图生成器",
            ["Live preview + tuning for the top-down map export (PhysX snapshot)."] = "实时预览 + 调整用于俯视地图导出（PhysX 快照）。",
            ["Command Palette"] = "命令面板",
            ["Close All"] = "关闭所有",
            ["透视设置"] = "透视设置",
            ["Switch radar preset.\nUse the 'Previous/Next Preset' hotkeys to cycle."] = "切换雷达预设。\n使用“上一个/下一个预设”热键循环。",

            // Status bar / top info (相关上部信息)
            ["STATUS"] = "状态",
            ["In Hideout"] = "在藏身处",
            ["STASH"] = "保险箱",
            ["In Raid"] = "在对局中",
            ["PLAYERS"] = "玩家",
            ["VITALS"] = "生命值",
            ["FPS"] = "帧率",
            ["DMA"] = "DMA",
            ["MAP"] = "地图",
            ["No Map"] = "无地图",
            ["Hide status bar"] = "隐藏状态栏",
            ["Show status bar"] = "显示状态栏",
            ["Config saved"] = "配置已保存",
            ["E {0}  ·  H {1}"] = "能 {0} · 水 {1}",

            // Command Palette
            ["Command Palette"] = "命令面板",
            ["Type to filter…"] = "输入以筛选…",
            ["(Ctrl+K · Esc to close · ↑/↓ to navigate · Enter to run)"] = "(Ctrl+K · Esc 关闭 · ↑/↓ 导航 · Enter 执行)",

            // Command Palette builtin items
            ["Open Settings"] = "打开设置",
            ["Open Hotkeys"] = "打开热键",
            ["Open Loot Filters"] = "打开物资过滤",
            ["Open Killfeed"] = "打开击杀播报",
            ["Open Player History"] = "打开玩家历史",
            ["Open Watchlist"] = "打开监视列表",
            ["Open Quest Planner"] = "打开任务规划器",
            ["Open Hideout"] = "打开藏身处",
            ["Toggle Sidebar"] = "切换侧边栏",
            ["Toggle Side Dock"] = "切换侧面板停靠",
            ["Reset Side Panels"] = "重置侧面板",
            ["Show Welcome Tour"] = "显示欢迎导览",
            ["打开透视设置"] = "打开透视设置",
            ["Panel"] = "面板",
            ["Layout"] = "布局",
            ["Help"] = "帮助",

            // Hotkey action DisplayNames and Categories (for command palette and hotkey UI)
            ["Battle Mode"] = "战斗模式",
            ["Free Mode"] = "自由模式",
            ["Zoom In"] = "放大",
            ["Zoom Out"] = "缩小",
            ["Toggle Loot"] = "切换物资",
            ["Toggle Containers"] = "切换容器",
            ["Toggle Corpses"] = "切换尸体",
            ["Toggle Exfils"] = "切换撤离点",
            ["Toggle Doors"] = "切换门",
            ["Toggle Aimview"] = "切换瞄准视角",
            ["Toggle Players On Top"] = "切换玩家置顶",
            ["Connect Groups"] = "连接组",
            ["Toggle ESP Window"] = "切换透视窗口",
            ["Cycle ESP Render Mode"] = "循环透视渲染模式",
            ["Toggle ESP Crosshair"] = "切换透视准星",
            ["Next Preset"] = "下一个预设",
            ["Previous Preset"] = "上一个预设",
            ["Sidebar: Players"] = "侧边栏：玩家",
            ["Sidebar: Loot"] = "侧边栏：物资",
            ["Sidebar: Aimview"] = "侧边栏：瞄准视角",
            ["Sidebar: Quests"] = "侧边栏：任务",
            ["Sidebar: Settings"] = "侧边栏：设置",
            ["Cycle Aimview Size"] = "循环瞄准视角大小",
            ["Cycle Aimview Corner"] = "循环瞄准视角角落",
            ["VisCheck Debug Window"] = "可见检查调试窗口",
            ["VisCheck Cache View"] = "可见检查缓存视图",
            ["VisCheck Rebuild Snapshot"] = "可见检查重建快照",
            ["VisCheck Generate Map"] = "可见检查生成地图",
            ["VisCheck Map Generator"] = "可见检查地图生成器",

            ["General"] = "通用",
            ["Widgets"] = "窗口",
            ["Presets"] = "预设",
            ["VisCheck"] = "可见检查",

            // Hotkey action tooltips (shown in hotkey UI and command palette context)
            ["Toggle battle mode (hide loot, focus players)"] = "切换战斗模式（隐藏物资，专注玩家）",
            ["Toggle between player-follow and free-pan"] = "在跟随玩家和自由平移之间切换",
            ["Zoom in on the radar map"] = "放大雷达地图",
            ["Zoom out on the radar map"] = "缩小雷达地图",
            ["Toggle loot overlay visibility"] = "切换物资叠加可见性",
            ["Toggle static container rendering on the radar"] = "切换雷达上静态容器渲染",
            ["Toggle corpse marker rendering on the radar"] = "切换雷达上尸体标记渲染",
            ["Toggle exfil point rendering on the radar"] = "切换雷达上撤离点渲染",
            ["Toggle keyed door rendering on the radar"] = "切换雷达上钥匙门渲染",
            ["Show/hide the aimview widget"] = "显示/隐藏瞄准视角窗口",
            ["Toggle drawing players above all other entities"] = "切换将玩家绘制在所有其他实体之上",
            ["Toggle squad connection lines"] = "切换小队连接线",
            ["Open/close the ESP overlay window"] = "打开/关闭透视叠加窗口",
            ["Cycle player render mode: None → Bones → Box → HeadDot"] = "循环玩家渲染模式：无 → 骨骼 → 方框 → 头点",
            ["Show/hide the center crosshair overlay on the ESP window"] = "显示/隐藏透视窗口中心准星叠加",
            ["Cycle to the next radar preset in your saved list, then Custom"] = "循环到已保存列表中的下一个雷达预设，然后自定义",
            ["Cycle to the previous radar preset"] = "循环到上一个雷达预设",
            ["Show/hide the left icon sidebar"] = "显示/隐藏左侧图标侧边栏",
            ["Toggle the fixed right-edge dock for Players / Loot / Quests panels"] = "切换玩家/物资/任务面板的固定右侧停靠",
            ["Toggle the Players widget (sidebar slot 1)"] = "切换玩家窗口（侧边栏槽位1）",
            ["Toggle the Loot widget (sidebar slot 2)"] = "切换物资窗口（侧边栏槽位2）",
            ["Toggle the Aimview widget (sidebar slot 3)"] = "切换瞄准视角窗口（侧边栏槽位3）",
            ["Toggle the Quests panel (sidebar slot 4)"] = "切换任务面板（侧边栏槽位4）",
            ["Toggle the Settings panel (sidebar slot 5)"] = "切换设置面板（侧边栏槽位5）",
            ["Cycle aimview PiP size: Floating → Small → Medium → Large"] = "循环瞄准视角画中画大小：浮动 → 小 → 中 → 大",
            ["Cycle aimview PiP corner: TL → TR → BR → BL"] = "循环瞄准视角画中画角落：左上 → 右上 → 右下 → 左下",
            ["Snap Players / Loot / Quests back into the right dock layout"] = "将玩家/物资/任务快照回右侧停靠布局",
            ["Toggle the VisCheck debug overlay (worker stats, Top Blockers, classifier rules)"] = "切换可见检查调试叠加（工作线程统计、顶级阻挡、分类规则）",
            ["Toggle the 3D wireframe Cache View (PhysX scene + live player overlay)"] = "切换3D线框缓存视图（PhysX场景 + 实时玩家叠加）",
            ["Force-rebuild the PhysX scene snapshot for the current map"] = "强制为当前地图重建PhysX场景快照",
            ["Generate a top-down SVG map + config from the current PhysX snapshot (writes to generated_maps/)"] = "从当前PhysX快照生成俯视SVG地图 + 配置（写入 generated_maps/）",
            ["Toggle the Map Generator panel (live preview + tuning for the top-down map export)"] = "切换地图生成器面板（实时预览 + 俯视地图导出调整）",
        };

        public static string T(string key)
        {
            return Ui.TryGetValue(key, out var value) ? value : key;
        }

        // ==================== Loot / 物资相关 ====================
        public static readonly Dictionary<string, string> Loot = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Loot Filters"] = "物资过滤",
            ["Show Loot"] = "显示物资",
            ["All Loot"] = "全部物资",
            ["Important+"] = "重要+",
            ["Wishlist"] = "愿望单",
            ["Quest"] = "任务物品",
            ["Hide everything below the Important threshold."] = "隐藏低于「重要」阈值的所有物品。",
            ["Quest + wishlist still bypass the filter."] = "任务和愿望单物品仍会显示。",
            ["Wishlist + quest items only."] = "仅显示愿望单和任务物品。",
            ["Clears category overrides so the map stays clean."] = "清除分类覆盖，使地图更清晰。",
            ["Price Threshold"] = "价格阈值",
            ["Important Threshold"] = "重要阈值",
            ["Loot Categories"] = "物资分类",
            ["Meds"] = "医疗物品",
            ["Food"] = "食物/饮料",
            ["Backpacks"] = "背包",
            ["Keys"] = "钥匙",
            ["Quest Items"] = "任务物品",
            ["Show Quest Items"] = "显示任务物品",
            ["Show Wishlist"] = "显示愿望单",
            ["Container"] = "容器",
            ["Corpse"] = "尸体",
            ["Airdrop"] = "空投",
            ["Visible"] = "可见",
            ["Total"] = "总数",

            // LootFiltersPanel UI
            ["Quick View"] = "快速视图",
            ["搜索"] = "搜索",
            ["按名称搜索…"] = "按名称搜索…",
            ["清除"] = "清除",
            ["按物品名称或简称过滤（不区分大小写）"] = "按物品名称或简称过滤（不区分大小写）",
            ["价格"] = "价格",
            ["快速设置最低价:"] = "快速设置最低价:",
            ["最低价 (₽)"] = "最低价 (₽)",
            ["重要阈值 (₽)"] = "重要阈值 (₽)",
            ["隐藏低于此价格的物资。\n点击 +/- 按钮或长按重复。"] = "隐藏低于此价格的物资。\n点击 +/- 按钮或长按重复。",
            ["将达到此价格的物资用绿色高亮。"] = "将达到此价格的物资用绿色高亮。",
            ["\u26a0 最低价高于重要阈值 — 不会有物品被高亮为重要。"] = "\u26a0 最低价高于重要阈值 — 不会有物品被高亮为重要。",
            ["仅重要"] = "仅重要",
            ["隐藏低于重要价格阈值的物资。\n愿望单、任务和分类物品仍会显示。"] = "隐藏低于重要价格阈值的物资。\n愿望单、任务和分类物品仍会显示。",
            ["始终显示"] = "始终显示",
            ["这些分类会绕过价格过滤。"] = "这些分类会绕过价格过滤。",
            ["Unknown Items"] = "未知物品",
            ["Show loose items whose BSG ID isn't in the tarkov.dev database\n(e.g. items added by a recent patch). Rendered with a placeholder label\nshowing the BSG ID prefix so they can be identified and reported."] = "显示 tarkov.dev 数据库中没有 BSG ID 的散落物资\n（例如最近补丁新增的物品）。使用占位标签显示 BSG ID 前缀，便于识别和报告。",
            ["Quest Loot Highlighting"] = "任务物资高亮",
            ["Marks loose loot needed for active quests. Respects Kappa-only and selected-quest filters."] = "标记活跃任务所需的散落物资。尊重仅 Kappa 和选定任务过滤器。",
            ["Highlight Quest-Required Loot"] = "高亮任务所需物资",
            ["Mark loose items on the radar that are needed for an active quest (Find in Raid, hand-overs, etc.)."] = "在雷达上标记活跃任务所需的散落物品（战场拾取、上交等）。",
            ["Show Static Quest Items"] = "显示静态任务物品",
            ["Always show items flagged as quest-only by the game (pocket watches,\nJaeger's letter, etc.) regardless of price or active-quest filter."] = "始终显示游戏标记为仅任务的物品（怀表、耶格尔信等），\n无论价格或活跃任务过滤器如何。",
            ["Hideout Upgrade Highlighting"] = "藏身处升级高亮",
            ["Marks loose loot needed for pending hideout upgrades.\nData is cached — highlighting works during raids using last-known planner state."] = "标记待定藏身处升级所需的散落物资。\n数据已缓存 — 在对局中使用最后已知规划器状态进行高亮。",
            ["Highlight Upgrade-Needed Loot"] = "高亮升级所需物资",
            ["Highlight any loose item still needed for a pending hideout upgrade.\nUses cached planner data — active even during raids."] = "高亮任何仍需用于待定藏身处升级的散落物品。\n使用缓存的规划器数据 — 即使在对局中也有效。",
            ["FiR Only Highlight"] = "仅战场拾取高亮",
            ["Highlight items that must be Found-in-Raid.\nWorks independently — you can disable the general highlight and keep only FiR items marked."] = "高亮必须为战场拾取 (FiR) 的物品。\n独立工作 — 你可以禁用通用高亮，只保留 FiR 标记。",
            ["Wishlist Settings"] = "愿望单设置",
            ["Show wishlisted items"] = "显示愿望单物品",
            ["Always show wishlisted items, bypassing price/category filters."] = "始终显示愿望单物品，绕过价格/分类过滤。",
            ["Use in-game wishlist"] = "使用游戏内愿望单",
            ["Include items you marked as favourites inside Tarkov itself\n(read live from the in-game WishlistManager)."] = "包含你在塔科夫内标记为收藏的物品\n（实时从游戏内 WishlistManager 读取）。",
            ["Include groups:"] = "包含分组：",
            ["Quests"] = "任务",
            ["Hideout"] = "藏身处",
            ["Trading"] = "交易",
            ["Equipment"] = "装备",
            ["Other"] = "其他",
            ["In-game Wishlist"] = "游戏内愿望单",
            ["Not in raid or wishlist is empty."] = "不在对局中或愿望单为空。",
            ["Wishlist & Blacklist"] = "愿望单与黑名单",
            ["Search items to add..."] = "搜索要添加的物品…",
            ["Remove from wishlist"] = "从愿望单移除",
            ["Add to wishlist"] = "添加到愿望单",
            ["Remove from blacklist"] = "从黑名单移除",
            ["Add to blacklist"] = "添加到黑名单",
            ["Wishlist ({0})"] = "愿望单 ({0})",
            ["Blacklist ({0})"] = "黑名单 ({0})",
            ["No wishlisted or blacklisted items.\nSearch above to add items."] = "没有愿望单或黑名单物品。\n在上方搜索以添加物品。",
            ["Options"] = "选项",
            ["Price Source"] = "价格来源",
            ["Which price to use for filtering and display:\n• Best — highest of flea and trader (default)\n• Flea Market — flea price (falls back to trader)\n• Trader — trader price (falls back to flea)"] = "用于过滤和显示的价格来源：\n• 最佳 — 跳蚤和商人中的最高价（默认）\n• 跳蚤市场 — 跳蚤价格（回退到商人）\n• 商人 — 商人价格（回退到跳蚤）",
            ["Price Per Slot"] = "每格价格",
            ["Divide price by item grid size.\nUseful for finding high-value-per-slot items."] = "将价格除以物品格子大小。\n有助于寻找高单格价值物品。",
            ["Show Corpses"] = "显示尸体",
            ["Show corpse X markers on the radar."] = "在雷达上显示尸体 X 标记。",
            ["Show Corpse Value"] = "显示尸体价值",
            ["Show total gear value on the corpse tooltip and aimview label."] = "在尸体悬浮提示和瞄准视角标签上显示总装备价值。",
            ["Show Corpse Inventory"] = "显示尸体库存",
            ["Show the per-slot equipment list on the corpse tooltip."] = "在尸体悬浮提示上显示每格装备列表。",
            ["Reset Defaults"] = "重置默认",
            ["Reset all loot filter settings to defaults"] = "将所有物资过滤设置重置为默认",
            ["Save Config"] = "保存配置",
            ["Save current settings to disk"] = "将当前设置保存到磁盘",

            // LootWidget related
            ["No loot matches current filters"] = "没有物资匹配当前过滤器",
            ["total value"] = "总价值",
            [" items"] = " 物品",
            ["highlighted on radar"] = "已在雷达上高亮",
            ["Clear pings"] = "清除标记",
            ["Remove all loot pings"] = "移除所有物资标记",
            ["Item"] = "物品",
            ["Price"] = "价格",
            ["Qty"] = "数量",
            ["Total"] = "总计",
            ["Dist"] = "距离",
            ["pinged"] = "已标记",
            ["hidden"] = "已隐藏",
        };

        // ==================== 设置面板常用文本 ====================
        public static readonly Dictionary<string, string> Settings = new(StringComparer.OrdinalIgnoreCase)
        {
            ["General"] = "通用",
            ["ESP"] = "透视",
            ["Map"] = "地图",
            ["Hotkeys"] = "热键",
            ["Presets"] = "预设",
            ["Quest Zones"] = "任务区域",

            ["Master Toggle"] = "总开关",
            ["Enabled"] = "已启用",
            ["Disabled"] = "已禁用",

            ["Radar"] = "雷达",
            ["Rendering"] = "渲染",
            ["Performance"] = "性能",
            ["Memory"] = "内存",
            ["UI"] = "界面",

            ["Follow Player"] = "跟随玩家",
            ["Free Look"] = "自由视角",
            ["Battle Mode"] = "战斗模式",
            ["Night Vision"] = "夜视",
            ["Thermal Vision"] = "热成像",

            // GeneralTab / Radar / Web
            ["Radar"] = "雷达",
            ["Restart Radar"] = "重启雷达",
            ["Restart the radar (re-detect game world, players, loot)"] = "重启雷达（重新检测游戏世界、玩家、物资）",
            ["Only available during a raid or in the hideout"] = "仅在活动对局或藏身处中可用",
            ["Port"] = "端口",
            ["Tick (ms)"] = "更新间隔 (ms)",
            ["HTTP port (requires restart to take effect)"] = "HTTP 端口（需要重启生效）",
            ["Update interval for the web radar data"] = "Web 雷达数据更新间隔",
            ["UPnP / NAT-PMP"] = "UPnP / NAT-PMP 自动端口映射",
            ["Automatically forward the port on your router via UPnP.\nEnables access from outside your network.\nTakes effect on next server start."] = "通过 UPnP 自动在路由器上转发端口。\n允许从外网访问。\n在下次服务器启动时生效。",
            ["Private:"] = "内网地址：",
            ["Public:"] = "公网地址：",
            ["Copy private (LAN) address to clipboard"] = "复制内网(LAN)地址到剪贴板",
            ["Copy public (WAN) address to clipboard"] = "复制公网(WAN)地址到剪贴板",
            ["Open in default browser"] = "在默认浏览器中打开",
            ["Running on port"] = "运行中，端口",
            ["Detecting..."] = "检测中...",
            ["Stopped"] = "已停止",
            ["Private:  Detecting..."] = "内网地址：检测中...",

            // Match dump / export
            ["Serialize all radar data (players, loot, corpses, exfils…) to a JSON file in the dumps\\ folder.\nUse the button below to trigger a snapshot manually."] = "将所有雷达数据（玩家、物资、尸体、撤离点…）序列化为 JSON 文件保存到 dumps\\ 文件夹。\n使用下方按钮手动触发快照。",

            // SettingsPanel footer
            ["Changes auto-saved"] = "更改自动保存",
        };

        // ==================== 预设相关 ====================
        public static readonly Dictionary<string, string> Presets = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Stealth"] = "隐蔽模式",
            ["Loot Run"] = "物资跑图",
            ["PvP"] = "PvP 模式",
            ["Quests"] = "任务模式",
            ["Custom"] = "自定义",
            ["Spotter"] = "观察员",
            ["Battle Buddy"] = "战斗伙伴",
            ["Loot Hunter"] = "物资猎手",
            ["Quest Helper"] = "任务助手",

            // Preset toggle labels (used in PresetsTab)
            ["Battle Mode"] = "战斗模式",
            ["Show Loot"] = "显示物资",
            ["Show Corpses"] = "显示尸体",
            ["Show Containers"] = "显示容器",
            ["Show Exfils"] = "显示撤离点",
            ["Show Doors"] = "显示门",
            ["Show Airdrops"] = "显示空投",
            ["Show Switches"] = "显示开关",
            ["Show Transits"] = "显示转运点",
            ["Show Aimlines"] = "显示瞄准线",
            ["Connect Groups"] = "连接同组",
            ["High Alert"] = "高警戒",
            ["Players On Top"] = "玩家置顶",

            // PresetsTab UI chrome
            ["Active:"] = "当前激活：",
            ["(drift — current toggles don't match any saved preset)"] = "(已偏离 — 当前开关与任何已保存预设不符)",
            ["Click Apply on any preset to switch. Edit toggles below to tweak."] = "点击任意预设的「应用」来切换。在下方编辑开关以调整。",
            ["built-in"] = "内置",
            ["user"] = "用户",
            ["Apply"] = "应用",
            ["Save current toggles"] = "保存当前开关",
            ["Overwrite this preset's stored toggle values\nwith the radar's current live state."] = "用雷达当前实时状态覆盖此预设存储的开关值。",
            ["Reset to defaults"] = "重置为默认",
            ["Restore name, description, and toggle values\nto the hardcoded baseline for this preset."] = "将名称、描述和开关值恢复为此预设的硬编码基线。",
            ["Confirm delete"] = "确认删除",
            ["Cancel"] = "取消",
            ["Delete"] = "删除",
            ["Edit"] = "编辑",
            ["Name"] = "名称",
            ["Description"] = "描述",
            ["Toggles (saved in this preset):"] = "开关（保存在此预设中）：",
            ["Save current radar state as a new preset"] = "将当前雷达状态保存为新预设",
            ["Captures all 13 toggles from the live radar into a new named preset."] = "将实时雷达的所有 13 个开关捕获到新命名预设中。",
            ["Save as new preset"] = "保存为新预设",
            ["Name is required."] = "名称为必填。",

            // Preset toggle tooltips (short)
            ["Hide non-combat clutter (loot / corpses / containers)."] = "隐藏非战斗杂物（物资/尸体/容器）。",
            ["Show loose loot items on the radar."] = "在雷达上显示散落物资。",
            ["Show dead player corpses (recent kills)."] = "显示死亡玩家尸体（最近击杀）。",
            ["Show static loot containers."] = "显示静态物资容器。",
            ["Show extraction points."] = "显示撤离点。",
            ["Show keyed / mechanical doors."] = "显示需要钥匙/机械门。",
            ["Show airdrop crates."] = "显示空投箱。",
            ["Show interactable switches / levers / buttons."] = "显示可交互开关/拉杆/按钮。",
            ["Show map-to-map transit points."] = "显示地图间转运点。",
            ["Show direction lines on player markers."] = "在玩家标记上显示方向线。",
            ["Draw lines between players in the same group."] = "为同一组的玩家绘制连线。",
            ["Extend aimline when an enemy is aiming at you."] = "当敌人瞄准你时延长瞄准线。",
            ["Draw players above loot / containers so dots stay visible."] = "将玩家绘制在物资/容器之上，使点保持可见。",
        };

        // ==================== 热键面板 ====================
        public static readonly Dictionary<string, string> Hotkeys = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Hotkeys"] = "热键",
            ["Hotkey Manager"] = "热键管理",
            ["Press a key..."] = "请按下一个按键...",
            ["Clear"] = "清除",
            ["Default"] = "默认",
            ["Conflict"] = "冲突",

            // HotkeysTab strings
            ["Input manager not initialized."] = "输入管理器未初始化。",
            ["Hotkeys require an active DMA connection. They will activate once a raid starts."] = "热键需要活动的 DMA 连接。将在对局开始后激活。",
            ["Manage hotkeys in the dedicated Hotkeys panel."] = "在专用的热键面板中管理热键。",
            ["Open Hotkey Manager"] = "打开热键管理器",
            ["Active Hotkeys"] = "激活的热键",
            ["No hotkeys configured."] = "未配置热键。",
            ["Toggle"] = "切换",
            ["OnKey"] = "按下时",

            // HotkeyManagerPanel
            ["Hotkeys"] = "热键",
            ["Input manager not initialized."] = "输入管理器未初始化。",
            ["Hotkeys require an active DMA connection. They will activate once a raid starts."] = "热键需要活动的 DMA 连接。将在对局开始后激活。",
            ["Hotkeys work via DMA — they read the gaming PC's keyboard state."] = "热键通过 DMA 工作 — 读取游戏 PC 的键盘状态。",
            ["Add Hotkey"] = "添加热键",
            ["All actions have hotkeys assigned."] = "所有操作都已分配热键。",
            ["Action"] = "操作",
            ["[ Press a key... ]"] = "[ 请按下一个按键... ]",
            ["(None)"] = "(无)",
            ["Press a key to bind, or Escape to cancel"] = "按下一个按键进行绑定，或按 Esc 取消",
            ["Click to capture a key"] = "点击以捕获按键",
            ["Toggle"] = "切换",
            ["OnKey (Hold)"] = "按下时 (保持)",
            ["Add Hotkey"] = "添加热键",
            ["Active Hotkeys"] = "激活的热键",
            ["No hotkeys configured."] = "未配置热键。",
            ["Key"] = "按键",
            ["Mode"] = "模式",
            ["Category"] = "分类",
            ["Remove this hotkey"] = "移除此热键",
        };

        public static string L(string key) => Loot.TryGetValue(key, out var v) ? v : key;
        public static string S(string key) => Settings.TryGetValue(key, out var v) ? v : key;
        public static string P(string key) => Presets.TryGetValue(key, out var v) ? v : key;
        public static string H(string key) => Hotkeys.TryGetValue(key, out var v) ? v : key;

        // ==================== ESP / 透视相关 ====================
        public static readonly Dictionary<string, string> Esp = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Players"] = "玩家",
            ["Show Players"] = "显示玩家",
            ["Render Mode"] = "渲染模式",
            ["Show Bones Inside Box"] = "在方框内显示骨骼",
            ["Max Distance"] = "最大距离",
            ["Loot"] = "物资",
            ["Show Loot"] = "显示物资",
            ["Crosshair"] = "准星",
            ["Show Crosshair"] = "显示准星",
            ["Style"] = "样式",
            ["Scale"] = "缩放",
            ["Crosshair Style Tooltip"] = "屏幕中心绘制的准星形状",
            ["Crosshair Scale Tooltip"] = "准星大小倍数",
            ["HUD"] = "HUD",
            ["Show FPS"] = "显示帧率",
            ["Show Status Text"] = "显示状态文本",
            ["Show Energy / Hydration"] = "显示能量/水分",
            ["Ballistics (debug)"] = "弹道 (调试)",
            ["Enable Ballistics"] = "启用弹道",
            ["Predicted Arc (red)"] = "预测轨迹 (红)",
            ["Live Tracers (green)"] = "实时弹道 (绿)",
            ["Debug HUD Window"] = "调试 HUD 窗口",
            ["Use Live G1 Table"] = "使用实时 G1 表格",
            ["Line Width"] = "线宽",
            ["Predicted Samples"] = "预测采样点",
            ["Predicted Max Distance"] = "预测最大距离",
            ["Live Shot Lifetime"] = "实时弹道持续时间",

            ["Grenades (ESP)"] = "手雷 (透视)",
            ["Enable Grenade ESP"] = "启用手雷轨迹",
            ["Grenade Max Distance"] = "手雷显示范围",
            ["Grenade Trail Lifetime"] = "手雷拖尾留存时间",
            ["Grenade Dot Size"] = "手雷点大小",
            ["Grenade Trail Width"] = "手雷轨迹线宽",

            // PlayersTab / Aimview settings (reused where possible)
            ["渲染"] = "渲染",
            ["玩家置顶"] = "玩家置顶",
            ["将玩家绘制在所有其他实体之上"] = "将玩家绘制在所有其他实体之上",
            ["连接组"] = "连接组",
            ["为同一组的玩家绘制连接线"] = "为同一组的玩家绘制连接线",
            ["瞄准线"] = "瞄准线",
            ["显示瞄准线"] = "显示瞄准线",
            ["在玩家标记上显示朝向方向线"] = "在玩家标记上显示朝向方向线",
            ["Length"] = "长度",
            ["Aimline length in pixels (human players)"] = "瞄准线长度（像素，人形玩家）",
            ["High Alert"] = "高警戒",
            ["Extend aimline when an enemy is aiming at you"] = "当敌人瞄准你时延长瞄准线",
            ["Aimview"] = "瞄准视角",
            ["Show Aimview"] = "显示瞄准视角",
            ["First-person projection widget showing nearby players"] = "显示附近玩家的第一人称投影小部件",
            ["Show Loot"] = "显示物资",
            ["Show nearby filtered loot items in the aimview"] = "在瞄准视角中显示附近已过滤的物资",
            ["Show Corpses"] = "显示尸体",
            ["Show nearby corpses with gear value in the aimview"] = "在瞄准视角中显示附近带装备价值的尸体",
            ["Show Containers"] = "显示容器",
            ["Show nearby static containers in the aimview"] = "在瞄准视角中显示附近静态容器",
            ["Show Skeleton"] = "显示骨骼",
            ["Draw bone skeleton for players (advanced aimview only).\nFalls back to a dot when off or skeleton data isn't ready yet."] = "为玩家绘制骨骼（仅高级瞄准视角）。\n关闭或骨骼数据未就绪时回退为点。",
            ["Show Player Labels"] = "显示玩家标签",
            ["Show \"Name (distance)\" labels under each player"] = "在每个玩家下方显示「名称(距离)」标签",
            ["Show Item Labels"] = "显示物品标签",
            ["Show labels under loot, corpse, and container markers.\nTurn off for a less cluttered view — markers stay visible."] = "在物资、尸体和容器标记下方显示标签。\n关闭可减少杂乱 — 标记仍可见。",
            ["Hide AI Players"] = "隐藏 AI 玩家",
            ["Hide Scav / Raider / Boss AI from the aimview.\nUseful on raids with many AI."] = "在瞄准视角中隐藏散兵/袭击者/Boss AI。\n在 AI 较多的对局中很有用。",
            ["Player Range"] = "玩家范围",
            ["Loot Range"] = "物资范围",
            ["Eye Height"] = "眼睛高度",
            ["Zoom"] = "缩放",
            ["Min Loot \u20bd"] = "最低物资价值",
            ["Max Loot"] = "最大物资数",
            ["Max Corpses"] = "最大尸体数",
            ["Max Containers"] = "最大容器数",
            ["Advanced Aimview"] = "高级瞄准视角",
            ["Use Advanced Aimview"] = "使用高级瞄准视角",
            ["Use real game camera data (ViewMatrix) for pixel-accurate\nprojection. Requires CameraManager — falls back to synthetic\ncamera if unavailable."] = "使用真实游戏相机数据（ViewMatrix）进行像素精确投影。\n需要 CameraManager — 不可用时回退到合成相机。",
            ["CameraManager not active — waiting for raid"] = "CameraManager 未激活 — 等待对局开始",
            ["Width of the monitor running EFT (pixels)"] = "运行 EFT 的显示器宽度（像素）",
            ["Height of the monitor running EFT (pixels)"] = "运行 EFT 的显示器高度（像素）",
        };

        public static string E(string key) => Esp.TryGetValue(key, out var v) ? v : key;

        // ==================== 地图标签页设置 ====================
        public static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Corpses"] = "尸体",
            ["Show Corpses"] = "显示尸体",
            ["Show corpse X markers on the radar"] = "在雷达上显示尸体 X 标记",
            ["Loot Markers"] = "物资标记",
            ["Dot Size"] = "点大小",
            ["Base radius of loot dots. Tier/important bumps are added on top."] = "物资点的基准半径。重要度会在此基础上增大。",
            ["Label Font"] = "标签字体",
            ["Font size of loot labels on the radar."] = "雷达上物资标签的字体大小。",
            ["Height Arrows (▲/▼)"] = "高度箭头 (▲/▼)",
            ["Show an up/down arrow on loot that is above or below your floor."] = "对高于或低于你所在楼层的物资显示上/下箭头。",
            ["Height Threshold"] = "高度阈值",
            ["Vertical distance (±m) before an arrow is drawn."] = "垂直距离超过此值(±米)时才绘制箭头。",
            ["Show Height (+/-m)"] = "显示高度差 (+/-m)",
            ["Append the exact vertical offset in meters to the loot label."] = "在物资标签后附加精确的垂直偏移米数。",
            ["Containers"] = "容器",
            ["Show Containers"] = "显示容器",
            ["Show static loot containers on the radar (duffle bags, toolboxes, etc.)"] = "在雷达上显示静态物资容器（挎包、工具箱等）",
            ["Show Names"] = "显示名称",
            ["Show container name labels next to markers"] = "在标记旁显示容器名称标签",
            ["Hide Searched"] = "隐藏已搜索",
            ["Hide containers that have been opened/searched"] = "隐藏已被打开/搜索过的容器",
            ["Exfils"] = "撤离点",
            ["Show Exfils"] = "显示撤离点",
            ["Show exfiltration points on the radar"] = "在雷达上显示撤离点",
            ["Hide Inactive"] = "隐藏未激活",
            ["Hide closed or unavailable exfils"] = "隐藏已关闭或不可用的撤离点",
            ["Transits"] = "转运点",
            ["Show Transits"] = "显示转运点",
            ["Show transit points (map-to-map travel) on the radar"] = "在雷达上显示地图间转运点",
            ["Doors"] = "门",
            ["Show Doors"] = "显示门",
            ["Show keyed doors on the radar"] = "在雷达上显示需要钥匙的门",
            ["Show Locked"] = "显示锁定",
            ["Show locked doors (red)"] = "显示锁定的门（红色）",
            ["Show Unlocked"] = "显示解锁",
            ["Show open or shut doors (green/orange)"] = "显示开启或关闭的门（绿/橙）",
            ["Only Near Valuable Loot"] = "仅靠近贵重物资",
            ["Only show doors near important (high-value) loot items"] = "仅显示靠近重要（高价值）物资的门",
            ["Proximity"] = "邻近距离",
            ["Max distance from door to valuable loot"] = "门到贵重物资的最大距离",
            ["Explosives & BTR"] = "爆炸物与 BTR",
            ["Show Explosives"] = "显示爆炸物",
            ["Show grenades, tripwires, and mortar projectiles on the radar"] = "在雷达上显示手雷、绊索和迫击炮弹",
            ["Show Tripwire Lines"] = "显示绊索线",
            ["Draw a line between tripwire endpoints"] = "在绊索端点之间绘制连线",
            ["Show BTR"] = "显示 BTR",
            ["Show the BTR armored vehicle on the radar (Streets/Woods)"] = "在雷达上显示 BTR 装甲车（街区/森林）",
            ["Show BTR Route Stops"] = "显示 BTR 路线停靠点",
            ["Show BTR route stop markers on the radar"] = "在雷达上显示 BTR 路线停靠标记",
            ["Killfeed Overlay"] = "击杀播报叠加",
            ["Show Killfeed Overlay"] = "显示击杀播报叠加",
            ["Draw kill events on the radar canvas (top-right corner).\nOpen the Killfeed panel (\u2620) for the full table and settings."] = "在雷达画布右上角绘制击杀事件。\n打开击杀播报面板（\u2620）查看完整表格和设置。",
            ["Max Entries"] = "最大条目",
            ["Maximum number of kill events visible at once"] = "同时可见的最大击杀事件数量",
            ["Entry TTL"] = "条目存活时间",
            ["Seconds before a killfeed entry fades out (5–600)."] = "击杀播报条目淡出前的秒数（5–600）。",
            ["Reset Killfeed Position"] = "重置击杀播报位置",
            ["Snap the killfeed overlay back to the top-right corner."] = "将击杀播报叠加层吸附回右上角。",
            ["Map Setup (Calibration)"] = "地图设置（校准）",
            ["No map loaded."] = "未加载地图。",
            ["Player position unavailable."] = "玩家位置不可用。",
            ["Map X"] = "地图 X",
            ["Map Y"] = "地图 Y",
            ["Map Scale"] = "地图缩放",
            ["Runtime calibration — adjust until your player marker\naligns with your real world position. Click 'Save Calibration'\nbelow to persist these values across restarts."] = "运行时校准 — 调整直到你的玩家标记与真实世界位置对齐。\n点击下方的「保存校准」以在重启后保持这些值。",
            ["Save Calibration"] = "保存校准",
            ["Persist the current Map X / Y / Scale to disk under map id '{0}'.\nReloaded automatically on next startup. Web radar clients pick up\nthe new values on their next tick."] = "将当前地图 X / Y / 缩放保存到磁盘，键为地图 ID '{0}'。\n下次启动时自动重新加载。Web 雷达客户端会在下一次更新时获取新值。",
            ["Reset to Bundled"] = "重置为内置",
            ["Remove the saved calibration for '{0}' and reload\nthe bundled defaults from the map JSON file."] = "移除 '{0}' 的已保存校准，并从地图 JSON 文件重新加载内置默认值。",
            ["(saved)"] = "(已保存)",
            ["Rotation"] = "旋转",
            ["0° (raw)"] = "0° (原始)",
            ["90° (left)"] = "90° (左转)",
            ["270° (right)"] = "270° (右转)",
            ["Visual rotation applied to tarkov.dev SVG maps. tarkov.dev's site\ndisplays them rotated 180° via Leaflet's CRS; pick the orientation\nyou prefer here. Markers re-align automatically."] = "应用于 tarkov.dev SVG 地图的视觉旋转。tarkov.dev 网站\n通过 Leaflet 的 CRS 将其旋转 180° 显示；在此选择你偏好的方向。\n标记会自动重新对齐。",
            ["Tarkov.dev SVG 地图"] = "Tarkov.dev SVG 地图",
            ["from assets.tarkov.dev 下载地图（Customs.svg, Woods.svg, ...）而不是使用内置 SVG。\n持久缓存于 %AppData%\\eft-dma-radar-silk\\tarkov-dev-maps\\.\nIgnored while Satellite Map is on. Falls back to bundled SVG on download failure."] = "从 assets.tarkov.dev 下载地图（Customs.svg, Woods.svg, ...）而不是使用内置 SVG。\n持久缓存于 %AppData%\\eft-dma-radar-silk\\tarkov-dev-maps\\。\n卫星地图开启时忽略。下载失败时回退到内置 SVG。",
        };

        public static string M(string key) => Map.TryGetValue(key, out var v) ? v : key;

        // ==================== 任务区域标签页设置 ====================
        public static readonly Dictionary<string, string> Quest = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Show Quest Zones"] = "显示任务区域",
            ["Master toggle — draw quest objective zones on the radar"] = "总开关 — 在雷达上绘制任务目标区域",
            ["Enable \"Show Quest Zones\" to configure options."] = "启用「显示任务区域」以配置选项。",
            ["Filters"] = "筛选",
            ["Kappa Only"] = "仅 Kappa",
            ["Only show quest zones for quests required to unlock the Kappa container"] = "仅显示解锁 Kappa 容器所需任务的任务区域",
            ["Show Optional Objectives"] = "显示可选目标",
            ["Include optional quest objectives in the radar display"] = "在雷达显示中包含可选任务目标",
            ["Objective Types"] = "目标类型",
            ["Kill Zones"] = "击杀区域",
            ["Show zones for \"eliminate\" / kill objectives"] = "显示「消灭」/击杀目标的区域",
            ["Find / Collect Zones"] = "寻找/收集区域",
            ["Show zones for \"find item\" / \"hand over item\" objectives"] = "显示「寻找物品」/「上交物品」目标的区域",
            ["Place / Plant Zones"] = "放置/安放区域",
            ["Show zones for \"mark\" / \"plant item\" objectives"] = "显示「标记」/「放置物品」目标的区域",
            ["Reach / Visit Zones"] = "到达/访问区域",
            ["Show zones for \"visit location\" and other movement objectives"] = "显示「访问地点」及其他移动目标的区域",
            ["Display"] = "显示",
            ["Show Names"] = "显示名称",
            ["Draw the quest name label next to each zone marker"] = "在每个区域标记旁绘制任务名称标签",
            ["Show Distance"] = "显示距离",
            ["Draw the distance (in metres) from the local player to each zone marker"] = "绘制从本地玩家到每个区域标记的距离（米）",
            ["Show Outlines"] = "显示轮廓",
            ["Draw the polygon outline of zone areas (where available)"] = "绘制区域的多边形轮廓（如果可用）",
            ["Distance Culling"] = "距离剔除",
            ["Limit Visibility Range"] = "限制可见范围",
            ["Only draw quest zones within a maximum distance from the local player.\nHelps reduce clutter on large maps."] = "仅在本地玩家最大距离内绘制任务区域。\n有助于减少大地图上的杂乱。",
            ["Max Distance"] = "最大距离",
            ["Quest zones farther than this distance are hidden"] = "超出此距离的任务区域将被隐藏",
        };

        public static string Q(string key) => Quest.TryGetValue(key, out var v) ? v : key;

        // ==================== 预设相关扩展 ====================
        // (extends existing Presets dict via P(), add more keys here)
    }
}
